/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedPostsRouteImport } from './routes/_authenticated/posts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as ApiPublicUpdatePostStatusRouteImport } from './routes/api/public/updatePostStatus'
import { Route as ApiPublicScheduleRouteImport } from './routes/api/public/schedule'
import { Route as ApiPublicPostsRouteImport } from './routes/api/public/posts'
import { Route as ApiPublicConnectAccountRouteImport } from './routes/api/public/connect-account'
import { Route as ApiPublicSplatRouteImport } from './routes/api/public/$'
import { Route as ApiPublicScheduleUpdatePostStatusRouteImport } from './routes/api/public/schedule/updatePostStatus'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPostsRoute = AuthenticatedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicUpdatePostStatusRoute =
  ApiPublicUpdatePostStatusRouteImport.update({
    id: '/api/public/updatePostStatus',
    path: '/api/public/updatePostStatus',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicScheduleRoute = ApiPublicScheduleRouteImport.update({
  id: '/api/public/schedule',
  path: '/api/public/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPostsRoute = ApiPublicPostsRouteImport.update({
  id: '/api/public/posts',
  path: '/api/public/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConnectAccountRoute = ApiPublicConnectAccountRouteImport.update({
  id: '/api/public/connect-account',
  path: '/api/public/connect-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSplatRoute = ApiPublicSplatRouteImport.update({
  id: '/api/public/$',
  path: '/api/public/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScheduleUpdatePostStatusRoute =
  ApiPublicScheduleUpdatePostStatusRouteImport.update({
    id: '/updatePostStatus',
    path: '/updatePostStatus',
    getParentRoute: () => ApiPublicScheduleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/posts': typeof AuthenticatedPostsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/public/connect-account': typeof ApiPublicConnectAccountRoute
  '/api/public/posts': typeof ApiPublicPostsRoute
  '/api/public/schedule': typeof ApiPublicScheduleRouteWithChildren
  '/api/public/updatePostStatus': typeof ApiPublicUpdatePostStatusRoute
  '/api/public/schedule/updatePostStatus': typeof ApiPublicScheduleUpdatePostStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/posts': typeof AuthenticatedPostsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/public/connect-account': typeof ApiPublicConnectAccountRoute
  '/api/public/posts': typeof ApiPublicPostsRoute
  '/api/public/schedule': typeof ApiPublicScheduleRouteWithChildren
  '/api/public/updatePostStatus': typeof ApiPublicUpdatePostStatusRoute
  '/api/public/schedule/updatePostStatus': typeof ApiPublicScheduleUpdatePostStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/posts': typeof AuthenticatedPostsRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/public/connect-account': typeof ApiPublicConnectAccountRoute
  '/api/public/posts': typeof ApiPublicPostsRoute
  '/api/public/schedule': typeof ApiPublicScheduleRouteWithChildren
  '/api/public/updatePostStatus': typeof ApiPublicUpdatePostStatusRoute
  '/api/public/schedule/updatePostStatus': typeof ApiPublicScheduleUpdatePostStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/accounts'
    | '/analytics'
    | '/dashboard'
    | '/posts'
    | '/schedule'
    | '/settings'
    | '/api/public/$'
    | '/api/public/connect-account'
    | '/api/public/posts'
    | '/api/public/schedule'
    | '/api/public/updatePostStatus'
    | '/api/public/schedule/updatePostStatus'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/accounts'
    | '/analytics'
    | '/dashboard'
    | '/posts'
    | '/schedule'
    | '/settings'
    | '/api/public/$'
    | '/api/public/connect-account'
    | '/api/public/posts'
    | '/api/public/schedule'
    | '/api/public/updatePostStatus'
    | '/api/public/schedule/updatePostStatus'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/accounts'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/posts'
    | '/_authenticated/schedule'
    | '/_authenticated/settings'
    | '/api/public/$'
    | '/api/public/connect-account'
    | '/api/public/posts'
    | '/api/public/schedule'
    | '/api/public/updatePostStatus'
    | '/api/public/schedule/updatePostStatus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiPublicSplatRoute: typeof ApiPublicSplatRoute
  ApiPublicConnectAccountRoute: typeof ApiPublicConnectAccountRoute
  ApiPublicPostsRoute: typeof ApiPublicPostsRoute
  ApiPublicScheduleRoute: typeof ApiPublicScheduleRouteWithChildren
  ApiPublicUpdatePostStatusRoute: typeof ApiPublicUpdatePostStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/posts': {
      id: '/_authenticated/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthenticatedPostsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/updatePostStatus': {
      id: '/api/public/updatePostStatus'
      path: '/api/public/updatePostStatus'
      fullPath: '/api/public/updatePostStatus'
      preLoaderRoute: typeof ApiPublicUpdatePostStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/schedule': {
      id: '/api/public/schedule'
      path: '/api/public/schedule'
      fullPath: '/api/public/schedule'
      preLoaderRoute: typeof ApiPublicScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/posts': {
      id: '/api/public/posts'
      path: '/api/public/posts'
      fullPath: '/api/public/posts'
      preLoaderRoute: typeof ApiPublicPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connect-account': {
      id: '/api/public/connect-account'
      path: '/api/public/connect-account'
      fullPath: '/api/public/connect-account'
      preLoaderRoute: typeof ApiPublicConnectAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/$': {
      id: '/api/public/$'
      path: '/api/public/$'
      fullPath: '/api/public/$'
      preLoaderRoute: typeof ApiPublicSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/schedule/updatePostStatus': {
      id: '/api/public/schedule/updatePostStatus'
      path: '/updatePostStatus'
      fullPath: '/api/public/schedule/updatePostStatus'
      preLoaderRoute: typeof ApiPublicScheduleUpdatePostStatusRouteImport
      parentRoute: typeof ApiPublicScheduleRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPostsRoute: typeof AuthenticatedPostsRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPostsRoute: AuthenticatedPostsRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicScheduleRouteChildren {
  ApiPublicScheduleUpdatePostStatusRoute: typeof ApiPublicScheduleUpdatePostStatusRoute
}

const ApiPublicScheduleRouteChildren: ApiPublicScheduleRouteChildren = {
  ApiPublicScheduleUpdatePostStatusRoute:
    ApiPublicScheduleUpdatePostStatusRoute,
}

const ApiPublicScheduleRouteWithChildren =
  ApiPublicScheduleRoute._addFileChildren(ApiPublicScheduleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiPublicSplatRoute: ApiPublicSplatRoute,
  ApiPublicConnectAccountRoute: ApiPublicConnectAccountRoute,
  ApiPublicPostsRoute: ApiPublicPostsRoute,
  ApiPublicScheduleRoute: ApiPublicScheduleRouteWithChildren,
  ApiPublicUpdatePostStatusRoute: ApiPublicUpdatePostStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
